### PR TITLE
Add py2neo version 3 URI compatibility

### PR DESCRIPTION
**Pull request by veleritas**
Hi Daniel,

Let me know if these changes are acceptable.

Toby

### CODE REVIEW

**Comment by dhimmel** [comment]
This PR continues https://github.com/dhimmel/hetio/pull/6. @veleritas any specific reason you opened a new PR?

**Comment by veleritas** [comment]
Wasn't sure how the PR would work since some commits from the old PR were rebased away, so I figured it was easier just to open a new one?

**Comment by dhimmel** [comment]
Will try to get this on PyPI today as v0.2.1.

**Comment by veleritas** [comment]
Isn't the current version already v0.2.1?

**Comment by dhimmel** [comment]
> Isn't the current version already v0.2.1?

Good catch. [PyPI](https://pypi.python.org/pypi/hetio) is currently at v0.2.1 but I forgot to make a [GitHub release](https://github.com/dhimmel/hetio/releases). So next version will be v0.2.2 and I'll look into continuous deployment.

**Comment by dhimmel** [comment]
> Wasn't sure how the PR would work since some commits from the old PR were rebased away, so I figured it was easier just to open a new one?

Yeah not a big deal. I probably would have force pushed after the rebase, but either is fine as long as they get linked in a comment.

**Pull request merged**
